### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by hyochan** [hyochan/dooboolab.com#2]
<img width="610" alt="Screen Shot 2021-01-18 at 1 48 07 AM" src="https://user-images.githubusercontent.com/27461460/104849835-428ffe00-592f-11eb-91f1-bbc285274bb0.png">

**Comment by hyochan** [comment]
![dooboo-coin](https://user-images.githubusercontent.com/27461460/147493821-1d95ae21-319a-410d-8a2c-4a69892080ec.png)

**Comment by hyochan** [comment]
https://user-images.githubusercontent.com/27461460/165814978-61fa6b01-e9cf-49ce-836e-b4977e35475f.mp4

**Comment by hyochan** [comment]
![dooboolab](https://raw.githubusercontent.com/dooboolab/dooboolab.com/eecbfd7db58ff6ce61ddf6383d67b5bff2fe1519/static/icon/dooboolab_logo_intro_cut.svg)

**Comment by seongjaeryu** [comment]
![dooboo-symbol-white](https://github.com/dooboolab/homepage/assets/17170511/d9550999-3f34-439a-bfe0-e3fb2013c40f)

**Comment by seongjaeryu** [comment]
![dooboo-symbol-purple](https://github.com/dooboolab/homepage/assets/17170511/79297835-9c87-4013-ad8f-17d04055b072)

**Comment by seongjaeryu** [comment]
![dooboo-app-icon](https://github.com/dooboolab/homepage/assets/17170511/724bc3de-a60b-40c2-be16-9f1a9755b001)
